#!/usr/bin/env python3
"""CLI and whole-file global instruction lifecycle for Statutor v0.4."""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import sys
from pathlib import Path

import statutor_global as substrate


GENERATED_HEADER = (
    b"<!-- Generated by Statutor global (D-0018). "
    b"Edit canonical sources, not this projection. -->\n"
)
COMMON_SCAFFOLD = b"""\
<!-- Canonical cross-project working agreements. Keep under 200 lines. -->
# Global agent instructions

<!-- Add only cross-project guidance. Project instructions take precedence. -->
"""


def _roots(args: argparse.Namespace) -> substrate.ResolvedRoots:
    return substrate.resolve_roots(
        home=args.home,
        config_root=args.config_root,
        state_root=args.state_root,
    )


def _config_path(roots: substrate.ResolvedRoots) -> Path:
    return Path(roots.config_root) / "global.json"


def _state_path(roots: substrate.ResolvedRoots) -> Path:
    return Path(roots.state_root) / "global-state.json"


def _load_config(roots: substrate.ResolvedRoots) -> dict[str, object]:
    path = _config_path(roots)
    if not path.is_file():
        raise substrate.GlobalError("global layer is not initialized; run `statutor global init`")
    return substrate.validate_config(substrate.load_json(path))


def _load_state(roots: substrate.ResolvedRoots) -> dict[str, object]:
    path = _state_path(roots)
    if not path.is_file():
        raise substrate.GlobalError("global state is missing; run `statutor global init`")
    return substrate.validate_state(substrate.load_json(path))


def _source_paths(
    roots: substrate.ResolvedRoots, config: dict[str, object], host: str
) -> tuple[Path, Path]:
    instructions = config["instructions"]
    assert isinstance(instructions, dict)
    overlays = instructions["overlays"]
    assert isinstance(overlays, dict)
    root = Path(roots.config_root)
    return root / str(instructions["common"]), root / str(overlays[host])


def instruction_target(roots: substrate.ResolvedRoots, host: str) -> Path:
    if host == "claude":
        return Path(roots.claude_home) / "CLAUDE.md"
    if host == "codex":
        return Path(roots.codex_home) / "AGENTS.md"
    if host == "opencode":
        return Path(roots.opencode_home) / "AGENTS.md"
    raise substrate.SchemaError(f"unsupported host: {host}")


def _append_section(output: bytearray, label: str, content: bytes) -> None:
    output.extend(f"\n<!-- statutor: {label} -->\n".encode("ascii"))
    output.extend(content)
    if content and not content.endswith(b"\n"):
        output.extend(b"\n")


def render_instruction(common: bytes, overlay: bytes, host: str) -> bytes:
    for label, content in (("common", common), (f"host={host}", overlay)):
        try:
            content.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise substrate.SchemaError(f"{label} instruction source is not UTF-8") from exc
    output = bytearray(GENERATED_HEADER)
    _append_section(output, "common", common)
    _append_section(output, f"host={host}", overlay)
    return bytes(output)


def _selected_hosts(config: dict[str, object], requested: list[str] | None) -> list[str]:
    configured = config["hosts"]
    assert isinstance(configured, list)
    if not requested:
        return list(configured)
    unknown = sorted(set(requested) - set(configured))
    if unknown:
        raise substrate.SchemaError(f"hosts are not enabled in config: {unknown}")
    return [host for host in configured if host in requested]


def _warnings(roots: substrate.ResolvedRoots, host: str, action: str) -> list[str]:
    warnings: list[str] = []
    if host == "codex":
        override = Path(roots.codex_home) / "AGENTS.override.md"
        if override.is_file() and override.stat().st_size > 0:
            warnings.append("Codex AGENTS.override.md shadows the managed base")
    if host == "opencode" and action == "create":
        fallback = Path(roots.claude_home) / "CLAUDE.md"
        if fallback.is_file() and fallback.stat().st_size > 0:
            warnings.append(
                "creating native OpenCode AGENTS.md suppresses its Claude fallback")
    return warnings


def instruction_plan(
    roots: substrate.ResolvedRoots,
    *,
    hosts: list[str] | None = None,
) -> dict[str, object]:
    config = _load_config(roots)
    state = _load_state(roots)
    artifacts = state["artifacts"]
    assert isinstance(artifacts, dict)
    items: list[dict[str, object]] = []
    warnings: list[str] = []
    for host in _selected_hosts(config, hosts):
        common_path, overlay_path = _source_paths(roots, config, host)
        if not common_path.is_file() or not overlay_path.is_file():
            raise substrate.GlobalError(f"instruction source missing for {host}")
        desired = render_instruction(
            common_path.read_bytes(), overlay_path.read_bytes(), host)
        desired_digest = substrate.content_digest(desired)
        desired_token = f"file:{desired_digest}:0600"
        target = instruction_target(roots, host)
        current = substrate.fingerprint(target)
        receipt = artifacts.get(f"instruction-{host}")
        if receipt is None:
            action = "create" if current.kind == substrate.ABSENT else "conflict"
            reason = None if action == "create" else "existing unmanaged target"
        else:
            substrate.validate_artifact_receipt(receipt)
            assert isinstance(receipt, dict)
            if current.token != receipt["installed_token"]:
                action = "conflict"
                reason = "managed target is missing or modified"
            elif current.token == desired_token:
                action = "noop"
                reason = None
            else:
                action = "update"
                reason = None
        item_warnings = _warnings(roots, host, action)
        warnings.extend(item_warnings)
        items.append({
            "host": host,
            "target": str(target),
            "current_token": current.token,
            "desired_digest": desired_digest,
            "desired_token": desired_token,
            "action": action,
            "reason": reason,
            "warnings": item_warnings,
        })
    plan = {
        "schema_version": substrate.SCHEMA_VERSION,
        "operation": "instruction-apply",
        "roots": roots.to_json(),
        "items": items,
        "warnings": warnings,
    }
    plan["plan_digest"] = substrate.content_digest(substrate.canonical_json(plan))
    return plan


def global_status(
    roots: substrate.ResolvedRoots,
    *,
    hosts: list[str] | None = None,
) -> dict[str, object]:
    plan = instruction_plan(roots, hosts=hosts)
    status_items = []
    for item in plan["items"]:
        assert isinstance(item, dict)
        action = item["action"]
        status = {
            "noop": "installed",
            "update": "outdated",
            "create": "missing",
            "conflict": "unmanaged-or-modified",
        }[str(action)]
        status_items.append({**item, "status": status})
    return {
        "schema_version": substrate.SCHEMA_VERSION,
        "roots": plan["roots"],
        "hosts": status_items,
        "warnings": plan["warnings"],
    }


def _init_files(roots: substrate.ResolvedRoots) -> list[tuple[Path, bytes]]:
    config_root = Path(roots.config_root)
    files: list[tuple[Path, bytes]] = [
        (_config_path(roots), substrate.canonical_json(substrate.default_config())),
        (config_root / "AGENTS.md", COMMON_SCAFFOLD),
    ]
    files.extend((config_root / f"hosts/{host}.md", b"") for host in substrate.HOSTS)
    files.append((_state_path(roots), substrate.canonical_json(substrate.default_state())))
    return files


def init_plan(roots: substrate.ResolvedRoots) -> dict[str, object]:
    actions = []
    for path, _ in _init_files(roots):
        current = substrate.fingerprint(path)
        action = "write" if current.kind == substrate.ABSENT else "skip"
        reason = None
        if current.kind not in {substrate.ABSENT, "file"}:
            action = "conflict"
            reason = "target is not a regular file"
        actions.append({
            "path": str(path), "action": action, "reason": reason,
            "current_token": current.token,
        })
    return {
        "schema_version": substrate.SCHEMA_VERSION,
        "operation": "global-init",
        "roots": roots.to_json(),
        "actions": actions,
    }


def global_init(roots: substrate.ResolvedRoots) -> list[dict[str, str]]:
    state_root = Path(roots.state_root)
    actions: list[dict[str, str]] = []
    with substrate.StateLock(state_root):
        files = _init_files(roots)
        for path, _ in files:
            current = substrate.fingerprint(path)
            if current.kind not in {substrate.ABSENT, "file"}:
                raise substrate.GlobalError(f"init target is not a regular file: {path}")
        if _config_path(roots).is_file():
            substrate.validate_config(substrate.load_json(_config_path(roots)))
        if _state_path(roots).is_file():
            substrate.validate_state(substrate.load_json(_state_path(roots)))
        for path, content in files:
            current = substrate.fingerprint(path)
            if current.kind == substrate.ABSENT:
                substrate.atomic_write_bytes(path, content, expected=substrate.ABSENT)
                actions.append({"action": "write", "path": str(path)})
            else:
                actions.append({"action": "skip", "path": str(path)})
        substrate.validate_config(substrate.load_json(_config_path(roots)))
        substrate.validate_state(substrate.load_json(_state_path(roots)))
    return actions


def _receipt(
    *,
    host: str,
    common_path: Path,
    target: Path,
    desired_digest: str,
    installed_token: str,
    backup_id: str,
) -> dict[str, object]:
    return {
        "kind": "instruction",
        "name": "global-instructions",
        "target_scope": host,
        "source_logical": str(common_path.absolute()),
        "source_real": str(common_path.resolve(strict=True)),
        "target_logical": str(target.absolute()),
        "target_real": str(target.resolve(strict=True)),
        "source_digest": desired_digest,
        "installed_token": installed_token,
        "backup_id": backup_id,
        "ownership": "statutor",
    }


def apply_instructions(
    roots: substrate.ResolvedRoots,
    *,
    hosts: list[str] | None = None,
) -> dict[str, object]:
    state_root = Path(roots.state_root)
    with substrate.StateLock(state_root):
        plan = instruction_plan(roots, hosts=hosts)
        conflicts = [item for item in plan["items"] if item["action"] == "conflict"]
        if conflicts:
            raise substrate.GlobalError("instruction plan has conflicts; nothing changed")
        changes = [item for item in plan["items"] if item["action"] in {"create", "update"}]
        if not changes:
            return plan
        config = _load_config(roots)
        state = _load_state(roots)
        state_path = _state_path(roots)
        state_expected = substrate.fingerprint(state_path).token
        operation_id = os.urandom(16).hex()
        journal_path, journal = substrate.create_journal(
            state_root,
            action="instruction-apply",
            plan_digest=str(plan["plan_digest"]),
            operation_id=operation_id,
        )
        journal, _ = substrate.update_journal(
            journal_path, journal, status="applying")
        installed: list[tuple[Path, Path, str]] = []
        artifacts = dict(state["artifacts"])
        backups = dict(state["backups"])
        state_committed = False
        try:
            for item in changes:
                host = str(item["host"])
                target = Path(str(item["target"]))
                common_path, overlay_path = _source_paths(roots, config, host)
                desired = render_instruction(
                    common_path.read_bytes(), overlay_path.read_bytes(), host)
                before_receipt = artifacts.get(f"instruction-{host}")
                backup_key = f"{operation_id}.{host}"
                manifest_path, _ = substrate.create_backup(
                    state_root,
                    target,
                    operation_id=operation_id,
                    artifact_id=host,
                )
                result = substrate.atomic_write_bytes(
                    target,
                    desired,
                    expected=str(item["current_token"]),
                    mode=0o600,
                )
                installed.append((target, manifest_path, result.token))
                initial_backup = (
                    str(before_receipt["backup_id"])
                    if isinstance(before_receipt, dict)
                    else backup_key
                )
                artifacts[f"instruction-{host}"] = _receipt(
                    host=host,
                    common_path=common_path,
                    target=target,
                    desired_digest=str(item["desired_digest"]),
                    installed_token=result.token,
                    backup_id=initial_backup,
                )
                backups[backup_key] = str(manifest_path.relative_to(state_root))
                journal, _ = substrate.update_journal(
                    journal_path,
                    journal,
                    status="applying",
                    step={"host": host, "status": "installed"},
                )
            updated_state = {
                **state,
                "generation": int(state["generation"]) + 1,
                "artifacts": artifacts,
                "backups": backups,
            }
            substrate.validate_state(updated_state)
            substrate.atomic_write_json(
                state_path, updated_state, expected=state_expected)
            state_committed = True
            substrate.update_journal(journal_path, journal, status="complete")
        except BaseException as error:
            if not state_committed:
                for target, manifest_path, installed_token in reversed(installed):
                    with contextlib.suppress(Exception):
                        substrate.restore_backup(
                            manifest_path, target, expected_current=installed_token)
            with contextlib.suppress(substrate.GlobalError):
                substrate.update_journal(
                    journal_path, journal, status="failed", error=str(error))
            raise
        return instruction_plan(roots, hosts=hosts)


def adoption_plan(
    roots: substrate.ResolvedRoots, host: str
) -> dict[str, object]:
    config = _load_config(roots)
    state = _load_state(roots)
    artifacts = state["artifacts"]
    assert isinstance(artifacts, dict)
    if f"instruction-{host}" in artifacts:
        raise substrate.GlobalError(f"{host} instruction target is already managed")
    target = instruction_target(roots, host)
    current = substrate.fingerprint(target)
    if current.kind != "file":
        raise substrate.GlobalError("adoption requires an existing regular file")
    common_path, overlay_path = _source_paths(roots, config, host)
    overlay = substrate.fingerprint(overlay_path)
    if overlay.kind != "file" or overlay_path.read_bytes() != b"":
        raise substrate.GlobalError("adoption requires an empty host overlay")
    original = target.read_bytes()
    common = common_path.read_bytes()
    desired = render_instruction(common, original, host)
    warnings = _warnings(roots, host, "adopt")
    if common.strip():
        warnings.append(
            "adoption adds the non-empty common source; effective behavior may change")
    return {
        "schema_version": substrate.SCHEMA_VERSION,
        "operation": "instruction-adopt",
        "host": host,
        "target": str(target),
        "current_token": current.token,
        "overlay": str(overlay_path),
        "desired_digest": substrate.content_digest(desired),
        "original_bytes_preserved": original in desired,
        "warnings": warnings,
    }


def adopt_instruction(roots: substrate.ResolvedRoots, host: str) -> dict[str, object]:
    preview = adoption_plan(roots, host)
    config = _load_config(roots)
    state_root = Path(roots.state_root)
    with substrate.StateLock(state_root):
        state = _load_state(roots)
        state_expected = substrate.fingerprint(_state_path(roots)).token
        artifacts = state["artifacts"]
        assert isinstance(artifacts, dict)
        if f"instruction-{host}" in artifacts:
            raise substrate.GlobalError(f"{host} instruction target is already managed")
        target = instruction_target(roots, host)
        current = substrate.fingerprint(target)
        if current.kind != "file":
            raise substrate.GlobalError("adoption requires an existing regular file")
        common_path, overlay_path = _source_paths(roots, config, host)
        overlay = substrate.fingerprint(overlay_path)
        if overlay.kind != "file" or overlay_path.read_bytes() != b"":
            raise substrate.GlobalError("adoption requires an empty host overlay")
        original = target.read_bytes()
        operation_id = os.urandom(16).hex()
        journal_path, journal = substrate.create_journal(
            state_root,
            action="instruction-adopt",
            plan_digest=substrate.content_digest(original),
            operation_id=operation_id,
        )
        journal, _ = substrate.update_journal(
            journal_path, journal, status="applying")
        target_manifest, _ = substrate.create_backup(
            state_root, target, operation_id=operation_id, artifact_id=host)
        overlay_manifest, _ = substrate.create_backup(
            state_root, overlay_path, operation_id=operation_id,
            artifact_id=f"{host}-overlay",
        )
        overlay_result: substrate.Fingerprint | None = None
        installed: substrate.Fingerprint | None = None
        state_committed = False
        try:
            overlay_result = substrate.atomic_write_bytes(
                overlay_path, original, expected=overlay.token)
            desired = render_instruction(common_path.read_bytes(), original, host)
            if original not in desired:
                raise substrate.GlobalError("adoption projection lost original bytes")
            installed = substrate.atomic_write_bytes(
                target, desired, expected=current.token, mode=0o600)
            backup_key = f"{operation_id}.{host}"
            updated = {
                **state,
                "generation": int(state["generation"]) + 1,
                "artifacts": {
                    **artifacts,
                    f"instruction-{host}": _receipt(
                        host=host,
                        common_path=common_path,
                        target=target,
                        desired_digest=substrate.content_digest(desired),
                        installed_token=installed.token,
                        backup_id=backup_key,
                    ),
                },
                "backups": {
                    **state["backups"],
                    backup_key: str(target_manifest.relative_to(state_root)),
                    f"{operation_id}.{host}-overlay": str(
                        overlay_manifest.relative_to(state_root)),
                },
            }
            substrate.validate_state(updated)
            substrate.atomic_write_json(
                _state_path(roots),
                updated,
                expected=state_expected,
            )
            state_committed = True
            substrate.update_journal(journal_path, journal, status="complete")
        except BaseException as error:
            if installed is not None and not state_committed:
                with contextlib.suppress(Exception):
                    substrate.restore_backup(
                        target_manifest, target, expected_current=installed.token)
            if overlay_result is not None and not state_committed:
                with contextlib.suppress(Exception):
                    substrate.restore_backup(
                        overlay_manifest,
                        overlay_path,
                        expected_current=overlay_result.token,
                    )
            with contextlib.suppress(substrate.GlobalError):
                substrate.update_journal(
                    journal_path, journal, status="failed", error=str(error))
            raise
    result = global_status(roots, hosts=[host])
    result["adoption_plan"] = preview
    return result


def uninstall_instructions(
    roots: substrate.ResolvedRoots,
    *,
    hosts: list[str] | None = None,
) -> dict[str, object]:
    config = _load_config(roots)
    state_root = Path(roots.state_root)
    selected = _selected_hosts(config, hosts)
    with substrate.StateLock(state_root):
        state = _load_state(roots)
        artifacts = dict(state["artifacts"])
        backups = state["backups"]
        assert isinstance(backups, dict)
        state_expected = substrate.fingerprint(_state_path(roots)).token
        restored: list[str] = []
        candidates: list[tuple[str, Path, dict, Path, str]] = []
        for host in selected:
            receipt = artifacts.get(f"instruction-{host}")
            if receipt is None:
                continue
            assert isinstance(receipt, dict)
            target = instruction_target(roots, host)
            current = substrate.fingerprint(target)
            if current.token != receipt["installed_token"]:
                raise substrate.GlobalError(f"refusing to uninstall modified {host} target")
            manifest_relative = backups.get(str(receipt["backup_id"]))
            if not isinstance(manifest_relative, str):
                raise substrate.GlobalError(f"missing initial backup for {host}")
            candidates.append((host, target, receipt, state_root / manifest_relative, current.token))
        if not candidates:
            return {"schema_version": 1, "restored": []}
        operation_id = os.urandom(16).hex()
        journal_path, journal = substrate.create_journal(
            state_root,
            action="instruction-uninstall",
            plan_digest=substrate.content_digest(substrate.canonical_json(selected)),
            operation_id=operation_id,
        )
        journal, _ = substrate.update_journal(journal_path, journal, status="applying")
        rollback: list[tuple[Path, Path, str]] = []
        state_committed = False
        try:
            for host, target, _, original_manifest, current_token in candidates:
                rollback_manifest, _ = substrate.create_backup(
                    state_root,
                    target,
                    operation_id=operation_id,
                    artifact_id=f"rollback-{host}",
                )
                result = substrate.restore_backup(
                    original_manifest, target, expected_current=current_token)
                rollback.append((target, rollback_manifest, result.token))
                artifacts.pop(f"instruction-{host}")
                restored.append(host)
                journal, _ = substrate.update_journal(
                    journal_path, journal, status="applying",
                    step={"host": host, "status": "restored"},
                )
            updated = {
                **state,
                "generation": int(state["generation"]) + 1,
                "artifacts": artifacts,
            }
            substrate.atomic_write_json(
                _state_path(roots), updated, expected=state_expected)
            state_committed = True
            substrate.update_journal(journal_path, journal, status="complete")
        except BaseException as error:
            if not state_committed:
                for target, manifest, current_token in reversed(rollback):
                    with contextlib.suppress(Exception):
                        substrate.restore_backup(
                            manifest, target, expected_current=current_token)
            with contextlib.suppress(substrate.GlobalError):
                substrate.update_journal(
                    journal_path, journal, status="failed", error=str(error))
            raise
    return {"schema_version": 1, "restored": restored}


def uninstall_plan(
    roots: substrate.ResolvedRoots,
    *,
    hosts: list[str] | None = None,
) -> dict[str, object]:
    config = _load_config(roots)
    state = _load_state(roots)
    artifacts = state["artifacts"]
    backups = state["backups"]
    assert isinstance(artifacts, dict) and isinstance(backups, dict)
    items = []
    for host in _selected_hosts(config, hosts):
        target = instruction_target(roots, host)
        current = substrate.fingerprint(target)
        receipt = artifacts.get(f"instruction-{host}")
        if receipt is None:
            action, reason = "noop", None
        elif current.token != receipt["installed_token"]:
            action, reason = "conflict", "managed target is missing or modified"
        elif str(receipt["backup_id"]) not in backups:
            action, reason = "conflict", "initial backup is missing"
        else:
            action, reason = "restore", None
        items.append({
            "host": host, "target": str(target), "action": action,
            "reason": reason, "current_token": current.token,
        })
    return {
        "schema_version": substrate.SCHEMA_VERSION,
        "operation": "instruction-uninstall",
        "roots": roots.to_json(),
        "items": items,
        "warnings": [],
    }


def _print_result(data: object, json_output: bool, *, file=sys.stdout) -> None:
    if json_output:
        print(json.dumps(data, sort_keys=True, indent=2), file=file)
    elif isinstance(data, list):
        for item in data:
            print(f"{item['action']:5} {item['path']}", file=file)
    elif isinstance(data, dict) and "items" in data:
        for item in data["items"]:
            suffix = f" — {item['reason']}" if item.get("reason") else ""
            print(
                f"{item['action']:8} {item['host']}: {item['target']}{suffix}",
                file=file,
            )
        for warning in data.get("warnings", []):
            print(f"WARN {warning}", file=file)
    else:
        print(json.dumps(data, sort_keys=True), file=file)


def _root_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--home")
    parser.add_argument("--config-root")
    parser.add_argument("--state-root")


def main(argv: list[str] | None = None) -> int:
    if argv and argv[0] == "skill":
        import statutor_skills
        return statutor_skills.main(argv[1:])
    parser = argparse.ArgumentParser(prog="statutor global")
    subparsers = parser.add_subparsers(dest="command", required=True)
    for name in ("init", "plan", "apply", "status", "uninstall"):
        child = subparsers.add_parser(name)
        _root_arguments(child)
        if name != "init":
            child.add_argument("--host", action="append", choices=substrate.HOSTS)
        child.add_argument("--json", action="store_true")
    adopt = subparsers.add_parser("adopt")
    _root_arguments(adopt)
    adopt.add_argument("host", choices=substrate.HOSTS)
    adopt.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    roots = _roots(args)
    try:
        if args.command == "init":
            _print_result(init_plan(roots), args.json, file=sys.stderr)
            result = global_init(roots)
        elif args.command == "plan":
            result = instruction_plan(roots, hosts=args.host)
        elif args.command == "apply":
            preview = instruction_plan(roots, hosts=args.host)
            _print_result(preview, args.json, file=sys.stderr)
            result = apply_instructions(roots, hosts=args.host)
        elif args.command == "status":
            result = global_status(roots, hosts=args.host)
        elif args.command == "adopt":
            preview = adoption_plan(roots, args.host)
            _print_result(preview, args.json, file=sys.stderr)
            result = adopt_instruction(roots, args.host)
        else:
            preview = uninstall_plan(roots, hosts=args.host)
            _print_result(preview, args.json, file=sys.stderr)
            result = uninstall_instructions(roots, hosts=args.host)
    except substrate.GlobalError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    _print_result(result, args.json)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except substrate.GlobalError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
